server:
  http:
    port: 9080
positions:
  filename: /var/loki/positions.yaml
clients:
  - url: http://loki:3100/loki/api/v1/push
scrape_configs:
  - job_name: varlogs
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /path/to/your/logs/*.log
